services:
  adonis:
    build:
      context: ./quaestum-challenge-backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info
      APP_KEY: EK-2H_5ojPAjd3XXUKgs4CDIJBj26Rnz
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: app
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      TZ: UTC
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  frontend:
    build:
      context: ./quaestum-challenge-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - adonis
